<?php
# Generated by the protocol buffer compiler.  DO NOT EDIT!
# source: user.proto

namespace User;

use Google\Protobuf\Internal\GPBType;
use Google\Protobuf\Internal\RepeatedField;
use Google\Protobuf\Internal\GPBUtil;

/**
 * Generated from protobuf message <code>user.RequestStudent</code>
 */
class RequestStudent extends \Google\Protobuf\Internal\Message
{
    /**
     * Generated from protobuf field <code>int64 student_id = 1;</code>
     */
    private $student_id = 0;
    /**
     * Generated from protobuf field <code>string mobile = 2;</code>
     */
    private $mobile = '';

    /**
     * Constructor.
     *
     * @param array $data {
     *     Optional. Data for populating the Message object.
     *
     *     @type int|string $student_id
     *     @type string $mobile
     * }
     */
    public function __construct($data = NULL) {
        \GPBMetadata\User::initOnce();
        parent::__construct($data);
    }

    /**
     * Generated from protobuf field <code>int64 student_id = 1;</code>
     * @return int|string
     */
    public function getStudentId()
    {
        return $this->student_id;
    }

    /**
     * Generated from protobuf field <code>int64 student_id = 1;</code>
     * @param int|string $var
     * @return $this
     */
    public function setStudentId($var)
    {
        GPBUtil::checkInt64($var);
        $this->student_id = $var;

        return $this;
    }

    /**
     * Generated from protobuf field <code>string mobile = 2;</code>
     * @return string
     */
    public function getMobile()
    {
        return $this->mobile;
    }

    /**
     * Generated from protobuf field <code>string mobile = 2;</code>
     * @param string $var
     * @return $this
     */
    public function setMobile($var)
    {
        GPBUtil::checkString($var, True);
        $this->mobile = $var;

        return $this;
    }

}

